### ISSUE TITLE
Add feature to find tasks by tag with task code

### ISSUE THREAD

**Issue by argrau** [a-castellano/toggl-jira-work-logger#10]

**Comment by a-castellano** [comment]
Hi @argrau 

I've created this issue in the actual [repo](https://git.windmaker.net/a-castellano/toggl-jira-work-logger/issues)

**Comment by a-castellano** [comment]
Hi @argrau, I have been made several changes in this app.

* Read JIRA task ID from tags if there is no tags defined in description.

If you have no ID in task description, the script will try to read it from tags.

You can test this new version using the develop image:
`docker run --rm  -it  --env-file=$HOME/.toggl-jira acastellano/toggl-jira-work-logger-develop toggl-jira-work-logger`

**Comment by a-castellano** [comment]
Hi @argrau , 

New release (Version 0.8.1-3), has been released.
