### ISSUE TITLE
Control layers

### ISSUE THREAD

**Issue by igarridot** [a-castellano/toggl-jira-work-logger#3]
In case of bad execution of the tool, like network or electric issues, if it occurs during scripts running maybe it can cause inapropiated task tagging and perhaps duplicate the time in next correct execution.

Maybe managing more than one label to control the tasks status can be useful to avoid duplicated tracking times.

**Comment by a-castellano** [comment]
Hi @igarridot ,

That's a great idea, few day ago I misspelled a group name and all work was logged but no time entry was tagged :( 

I am going to work on this issue as soon as possible.

Thanks for your feedback!

Cheers.

**Comment by igarridot** [comment]
Hi @a-castellano

It works! I used the tool with your changes and it works amazing! Now the tool can manage the marked as failes entries and avoid duplicate registers. 

Thanks!
