### ISSUE TITLE
Add arguments --today, --week

### ISSUE THREAD

**Issue by vicdoz** [a-castellano/toggl-jira-work-logger#9]
Hi,

The way to use the tool is logging a time interval. 

Can you add some arguments to make work easier?

>`toggl-jira-work-logger --today`

instead of 

>`toggl-jira-work-logger 2019-02-02 2019-02-02 15 `

Another examples:

>`toggl-jira-work-logger --week`
>`toggl-jira-work-logger --month`

I will appreciate you response.

Cheers!

**Comment by a-castellano** [comment]
Hi @vicdoz 

What a cool idea! I will work on it as soon as I end with [this issue](https://git.windmaker.net/a-castellano/toggl-jira-work-logger/issues/4) and docker usage is documented.

Cheers

**Comment by a-castellano** [comment]
Issue migrated [here](https://git.windmaker.net/a-castellano/toggl-jira-work-logger/issues/11).

**Comment by a-castellano** [comment]
Hi @vicdoz 

I've just make an update allowing arguments for special dates (today, week, and month)

You should be able to test using the develop image:

```docker run --rm  -it  --env-file=$HOME/.toggl-jira acastellano/toggl-jira-work-logger-develop toggl-jira-work-logger --week  --visibility-owner-name=Developers
Unable to find image 'acastellano/toggl-jira-work-logger-develop:latest' locally
latest: Pulling from acastellano/toggl-jira-work-logger-develop
38e2e6cd5626: Pull complete
705054bc3f5b: Pull complete
c7051e069564: Pull complete
7308e914506c: Pull complete
c750eb9df3bb: Pull complete
643956356c92: Pull complete
75fb7a7e65b3: Pull complete
bd18976492fd: Pull complete
2fdd11fc1843: Pull complete
Digest: sha256:d6426b3c8a466c073916d97aeedd0fdd2bcf1e6f025821e1d8a8f3f48ed7a7ef
Status: Downloaded newer image for acastellano/toggl-jira-work-logger-develop:latest
Processing entries from 2019-02-24
There was no entries for that date.
Processing entries from 2019-02-25
There was no entries for that date.
Processing entries from 2019-02-26
There was no entries for that date.
Processing entries from 2019-02-27
There was no entries for that date.
Processing entries from 2019-02-28
There was no entries for that date.
Processing entries from 2019-03-01
There was no entries for that date.
Processing entries from 2019-03-02
There was no entries for that date.
All Done
```

¿Could you please check if it works as expected?

Thank you.

**Comment by a-castellano** [comment]
Master has been updated too.

**Comment by a-castellano** [comment]
Time to close this issue, it has been already validated.
